name: Assign Issues

on:
    issues:
        types: [opened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: 'Auto-assign issue'
              uses: pozil/auto-assign-issue@v2
              with:
                  assignees: Glowstudent777
                  allowSelfAssign: false
